name: Example of GitHub Actions workflow to builds a Next.js site and and deploy it to AWS S3

on:
  # This workflow will run on pushes targeting the main branch
  push:
    branches: 
      - 'main'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: yarn install
      - name: Build with Next.js
        run: yarn build
      - name: Static HTML export with Next.js
        run: yarn export
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: export
          path: out
          
  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with: 
          name: export
      - name: Configures AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: ls
      - name: Deploy to S3 bucket
        run: aws s3 sync . s3://ghactionsnext
